server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:./data/coindesk # 存在專案目錄下
    driver-class-name: org.h2.Driver
    username: cdsa
    password: 2yZQA9xD9UrbNtJY

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generate-ddl: true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop

